######################################################################
# Automatically generated by qmake (3.0) Thu Jul 6 17:02:50 2017
######################################################################

TEMPLATE = app
TARGET = hexpuzzle
INCLUDEPATH += .

# Input
HEADERS += pieces.h HexDisplay.h
SOURCES += puzzle.cpp HexDisplay.cpp

CONFIG += c++11
QT += widgets