######################################################################
# Automatically generated by qmake (3.0) Thu Jul 6 17:02:50 2017
######################################################################

TEMPLATE = app
TARGET = Puzzle
INCLUDEPATH += .

# Input
HEADERS += Pieces.h HexDisplay.h SolutionWindow.h
SOURCES += Puzzle.cpp HexDisplay.cpp SolutionWindow.cpp

CONFIG += c++11
QT += widgets